# Generated by Django 3.0.7 on 2020-06-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
