# Generated by Django 3.0.7 on 2020-06-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Web_app', '0002_auto_20200619_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
