# Generated by Django 3.0.7 on 2020-06-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Web_app', '0003_auto_20200619_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
    ]
